### ISSUE TITLE
Domain not redirecting

### ISSUE THREAD

**Issue by wboykinm** [Valadian/SandersHealthcareCalculator#13]
For some reason (even though CNAME looks configured correctly) I get redirected to the clunkier gh-pages URL when I hit `sandershealthcare.com`

@Valadian Would you like me to switch the URL to `berniecare.org`? I've been pointing it at [a different savings calculator](https://github.com/wboykinm/berniecare), but yours is more polished and comprehensive. I've already set up a masked redirect for `berniecare.org --> valadian.github.io/SandersHealthcareCalculator/`, but I'm happy to issue a PR to the CNAME if you'd like that as the home domain of this site.

**Comment by Valadian** [comment]
I spent some time working on the alias and it never worked for me.  So I
left it at the redirect. Unfortunately you can only have one cname
redirect,  and I would prefer sandershealthcare.com. I am fine with
Berniecare.org redirecting (though I purposely avoided the term). I guess I
need to spend some time on it again.

It is awkward to test because it takes down the URL when I do.

**Comment by wboykinm** [comment]
No worries. I'll leave the redirect. Good luck with the CNAME!
